# Generated by Django 3.1.5 on 2021-01-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0002_auto_20210108_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='scan',
            field=models.ImageField(upload_to='scans'),
        ),
    ]
