# Generated by Django 3.1.5 on 2021-01-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0003_auto_20210108_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='scan',
            field=models.ImageField(upload_to=''),
        ),
    ]
